### PR TITLE
Issue #350

### LINKED ISSUE #350: dataCite reserve error on title
## 📜 To Reproduce
1. Run the command:
```
     pds-doi-cmd reserve -s loubrieu@jpl.nasa.gov -i ~/Downloads/DOI_reserve_template.1bebacc3.xlsx --node eng
```

With following file 
[DOI_reserve_template.1bebacc3.xlsx](https://github.com/NASA-PDS/doi-service/files/9262538/DOI_reserve_template.1bebacc3.xlsx)

3. See error:
```
Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/src/pds_doi_service/core/outputs/web_client.py", line 89, in _submit_content
    response.raise_for_status()
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/venv/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.test.datacite.org/dois
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/src/pds_doi_service/core/actions/reserve.py", line 253, in run
    output_doi, o_doi_label = self._web_client.submit_content(
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/src/pds_doi_service/core/outputs/datacite/datacite_web_client.py", line 81, in submit_content
    response_text = super()._submit_content(
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/src/pds_doi_service/core/outputs/web_client.py", line 95, in _submit_content
    raise WebRequestException(
pds_doi_service.core.entities.exceptions.WebRequestException: DOI submission request to DataCite service failed, reason: 404 Client Error: Not Found for url: https://api.test.datacite.org/dois
Details: ('{"errors":[{"status":"404","title":"The resource you are looking for '
 'doesn\'t exist."}]}')
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/venv/bin/pds-doi-cmd", line 33, in <module>
    sys.exit(load_entry_point('pds-doi-service', 'console_scripts', 'pds-doi-cmd')())
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/src/pds_doi_service/core/cmd/pds_doi_cmd.py", line 42, in main
    output = action.run(**kwargs)
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/src/pds_doi_service/core/actions/reserve.py", line 284, in run
    raise CriticalDOIException(err)
pds_doi_service.core.entities.exceptions.CriticalDOIException: DOI submission request to DataCite service failed, reason: 404 Client Error: Not Found for url: https://api.test.datacite.org/dois
Details: ('{"errors":[{"status":"404","title":"The resource you are looking for '
 'doesn\'t exist."}]}')
```

## 🕵️ Expected behavior

The reserve action should work, it used to work...

## 📚 Version of Software Used

Latest snapshot version

## 🖥 System Info

---

### PR DESCRIPTION
**Pull request by alexdunnjpl**
## 🗒️ Summary
Resolves #350 (probably - given the fact that I was able to replicate @tloubrieu-jpl's experience with a fresh development environment and the fact that the error should have affected anyone using a venv and a user-defined config, I'm gonna guess this is the cause).

The path to the user-defined config at the project/repository root was incorrectly being resolved via `sys.prefix` (which is something like `path/to/doi-service/venv` when a venv is in use), and a logging bug was hiding the fact that the user-defined config was not being found/used.

This PR also fixes the logging bug, adds some explanatory context to the 404 response returned by DataCite, and improves the articulation of some comments and symbols.

## ⚙️ Test Data and/or Report
Unit tests pass (except `flake8` lint)

## ♻️ Related Issues
closes #350

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
This is fine on paper 😁

However, there are a few practices here I take exception to. Sorry! 🙇‍♀️

1. Almost any reference to `__file__` is better served by the `pkg_resources` API. Using `__file__` in `constants.py` means the code will never properly run out of a wheel or egg. The `setup.cfg` better have `zip_safe = False` in it. 

2. However, the use of `__file__` in `constants.py` makes this even more brittle, because any use of `PROJECT_SRC_DIR` assumes you're working in a cloned repository with a `src` dir in it—never a _released egg_. Maybe that's okay for the DOI service? Is `PROJECT_SRC_DIR` actually used?

3. It feels weird that a utility function to get the logger also calls `logging.basicConfig`. This has the effect of overriding any user-specified configuration for logging that might be in place, such as for debugging a certain problem. This would be especially egregious for framework code, but I suppose the DOI Service isn't a framework 😆

4. Maybe `PROJECT_ROOT_DIR` should just be `os.getcwd()`? Or—hear me out—it could have several fallbacks, such as finding `pds_doi_service.ini` by a `--config SERVICE.INI` command-line option. Not found? Then `${PWD}/pds_doi_service.ini`. Not found? Then `${HOME}/.config/pds-doi-serivce/default.ini` → `/usr/local/etc/pds-doi-service/default.ini` → /etc/pds-doi-service/default.ini`. That way, it'd behave more like other Unix programs.

**Comment by alexdunnjpl** [comment]
@nutjob4life hey, I'm grateful for the conscientious review!

1/2 - `PROJECT_SRC_DIR` isn't used, it just seemed like a maybe-useful thing to include at the time.  Given that it's actually the *opposite* of useful, for the reasons you've given, I think the best approach is to nuke it and avoid the issue entirely.

3 - The (only) existing interface for user-specified logging I could see is the logging_level configuration value, so being new I figured I'd not rock the boat too much on that score. My thought is that anyone who needs to dig deeper than that is going to find it trivial to make whatever temporary changes they need in the logging code.

4 - I don't think you're wrong, but I'm too new to *agree* - I was deferring to the documentation, which states that the non-dev user-defined configuration can/should be provided in the repository/project root.  `os.getcwd()` is not fit for (that) purpose, unless I'm misunderstanding.  I do think that the current configuration approach is _generally_ confusing, in terms of "use the default config from core/wherever but overwrite with values in $PROJECT_ROOT/pds_doi_service.ini if exists but overwrite with values in $some_other_dir_for_dev_cfg/pds_doi_service.ini if exists.  That seems worth a new ticket in and of itself though.

Who are the core stakeholders/design-authorities on this repo besides @tloubrieu-jpl ?  I'm not sure with whom I need to be talking to about design change suggestions where I'm not absolutely certain I'm not missing some context.

**Comment by alexdunnjpl** [comment]
Re-tested after removing `PROJECT_SRC_DIR`, unit tests pass.

**Comment by jordanpadams** [comment]
@alexdunnjpl you can discuss some of these changes with @tloubrieu-jpl , @jimmie , @viviant100 and myself. Kind of a team design effort here

**Comment by nutjob4life** [comment]
> That seems worth a new ticket in and of itself though

This ↑

I'm still +1 to merge this PR but making finding configuration files following familiar patterns should be a separate goal.

**Comment by nutjob4life** [comment]
FYI, this might satisfy @sonatype-lift:
```python
def get_logger(name: str | None = None, logging_level: int = logging.INFO):
```

**Comment by alexdunnjpl** [comment]
Well looks like I get to learn two nice little bits of sugar today (as opposed to `Union[str, None]`... tyvm!

Python 3.10 really seems to be bringing the goods.

Will open a new PR since I can't figure out how to restore/reattach the branch.

**Comment by nutjob4life** [comment]
My "other" project is on 3.10 and _I am loving it_ 🥹

**Pull request merged**
