### PR TITLE
Issue 335 copyright metadata

### LINKED ISSUE #335: As a DOI user, I would like to know the copyright for PDS data
## 💪 Motivation
...so that I can understand how I am allowed to use this data.

### AC1: New DOI
**Given** a data set requiring a new DOI
**When I perform** the steps to create a DOI
**Then I expect** "US Government Works" copyright included in the DOI metadata submitted to DataCite

### AC2: Update existing DOI
**Given** an existing DOI that was created prior to this ticket creation
**When I perform** a query for the DOI
**Then I expect** "US Government Works" copyright has been updated and included in the DOI metadata

### PR DESCRIPTION
**Pull request by alexdunnjpl**
## 🗒️ Summary
Implements a rights-management statement class, adds rights management (`rightsList`) metadata to DataCite reservations and `DOIDataCiteRecord`s, and sets rights-management metadata to a US government-works copyright, by default 

## ⚙️ Test Data and/or Report
All tests pass except flake8 lint, no tests added.

## ♻️ Related Issues
fixes #335

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
Legit 👍

**Comment by jordanpadams** [comment]
@alexdunnjpl @nutjob4life holding on merging this for the time being. awaiting some feedback from our PDS DOI expert to ensure we are doing this right :-)

**Comment by jordanpadams** [comment]
@alexdunnjpl you may be able to just add the [licensing metadata update](https://github.com/NASA-PDS/doi-service/issues/224) to this PR in the meantime.

**Comment by alexdunnjpl** [comment]
Behaviour as-implemented:

 - new DOIs get GWorks and CC0 by default
 - `release` applied with no `rightsList` attribute present in label data gets GWorks and CC0
 - `release` applied with empty or other-valued `rightsList` attribute in label data gets whatever the label specifies.
 
 @jordanpadams ready to merge, pending your DOI MVP A-OK :sweat_smile:

**Comment by jordanpadams** [comment]
@alexdunnjpl do we need to update the [test data that is out there](https://github.com/NASA-PDS/doi-service/blob/issue-335-copyright-metadata/tests/data/)?

**Comment by jordanpadams** [comment]
merging. will poke at test data if anything breaks.

**Comment by alexdunnjpl** [comment]
@jordanpadams I can't turn up any string references to these files and the [commit histories](https://github.com/NASA-PDS/doi-service/commits/issue-335-copyright-metadata/tests/data/valid_bundle_doi.xml) are intractably-large in terms of identifying related files/modules/tests.

Given that tests aren't failing, I'd suggest it's not worth investigating further.

**Pull request merged**
